### ISSUE TITLE
Add full API reference to Docs

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#115]
Currently, not the whole API is visible in the docs. Not all modules can be found. We need to add this before the initial release.

For example there are no games in docs:

![image](https://github.com/mmschlk/shapiq/assets/45100845/7648b468-b13c-4d33-afb1-cff7e54ae95b)

## Tasks
- [ ] Automate API Reference Creation
- [ ] Test the deployed docs.

**Comment by AlessandroPierro** [comment]
Working on it.

**Comment by hbaniecki** [comment]
fixed
