### ISSUE TITLE
Player names for InteractionValues and Games

### ISSUE THREAD

**Issue by FFmgll** [mmschlk/shapiq#139]
Currently, all methods are dependent only on the number of players n. It would be useful to be able to work with individual player names. Applications could be to compute values for sub-games.
Possible ideas:
- player_names list (mapping) for each Game
- transformation methods for interactionvalues to re-label
- player_names list (mapping) for InteractionValues

**Comment by mmschlk** [comment]
Removing this from 1.0 as it is not important atm.

**Comment by mmschlk** [comment]
Putting this out of scope atm.
