### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#16]
Add progress tracker to approximators to monitor how much budget was used. 

Think about occasionally printing the InteractionValues.

**Comment by mmschlk** [comment]
This should be a verbosity thing just for printing displaying and not a "how good are my estimates at this point in time because I am checking variance and what-not" type of thing.

**Comment by AlessandroPierro** [comment]
I'll take care of this one, adding some progress bar using tqdm.

**Comment by mmschlk** [comment]
@AlessandroPierro, I think this might be a bit more tricky than I thought back then when I created this issue. Some approximators create a big matrix of coalitions and give this to the model function / game to evaluate. There much time is spent warranting a tqdm. Some other approximators are more easy and have a big for loop already in the estimation making pbars again easy to implement.
