### ISSUE TITLE
We could add the Uncertainty Game like InfoSHAP

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#160]
recreate the [InfoSHAP](https://openreview.net/forum?id=6rabAZhCRS&referrer=%5Bthe%20profile%20of%20Ido%20Guy%5D(%2Fprofile%3Fid%3D~Ido_Guy1)) as a Game maybe using conditional imputer instead of marginal imputation.

**Comment by pwhofman** [comment]
On it :sunglasses:

**Comment by mmschlk** [comment]
> On it 😎

Cool!
