### ISSUE TITLE
rethink index in run_benchmark()

### ISSUE THREAD

**Issue by hbaniecki** [mmschlk/shapiq#171]
perhaps it can "override" the index in approximators
```python
sv_approximators = [
    shapiq.PermutationSamplingSII(n=n_players, index="k-SII", random_state=0), 
    shapiq.SHAPIQ(n=n_players, random_state=0),
    shapiq.SVARMIQ(n=n_players, random_state=0), 
    shapiq.KernelSHAPIQ(n=n_players, random_state=0)
]
# run the benchmark with the chosen parameters
results = shapiq.games.benchmark.run_benchmark(
    index="k-SII",
    order=2,
    games=games,
    approximators=sv_approximators,
    save_path="benchmark_results.json",
    budget_steps=[500, 1000, 2000, 4000],
    n_jobs=8
)
```

**Comment by mmschlk** [comment]
This is not really possible. The benchmark has multiple ways of instantiating and using approximators. They can be specified via a str, class, or already instantiated object. For a more flexible usage (e.g. using approximators for different indices that they are intended for) we leave the logic as is: An `index` must always be specified.
