### ISSUE TITLE
Allow „Subsetting“ of InteractionValues

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#276]
Allow to turn an InteractionValues object into another InteractionValues with only a subset of players part of the new one. This is helpful for plotting only a selection of interesting players and potentially other cool things down the line.

**Comment by r-visser** [comment]
Would the objective be to create something similar to get_top_k_interactions, but instead supplying a subset of players and only retaining those values which belong to (at least) one of the players?

**Comment by mmschlk** [comment]
Yes, what I meant: So basically $C = A \setminus B$ where $A$ and $B$ are both sets of players, and $C$ is just the set-difference of both. Then all interactions with $B$ are removed and $C$ contains only interactions that can be made up of players in $A$.
