### ISSUE TITLE
Enhancing/Fixing main example in the documentation

### ISSUE THREAD

**Issue by jreivilo** [mmschlk/shapiq#279]
Hey everyone,

Thank you so much for the implementation of your paper. 

The doc I am refering is this one : https://shapiq.readthedocs.io/en/latest/notebooks/sv_calculation.html#Explainable-AI-with-Shapley-Values

In your example, I truly don't think Alice, should obtain the highest Shap Value because her contributions are smaller compared to others without deep diving in the math knowing the "coeficient" is the same for everyone.

Are you sure about that ?

Thank you!

**Comment by mmschlk** [comment]
Uh haha, I changed the values in the code but not in the markdown table before it. You are right! Code/interpretation and the description mismatch!

Thank you for pointing this out and checking out the repo!
