### ISSUE TITLE
Where Marmot?

### ISSUE THREAD

**Issue by mwever** [mmschlk/shapiq#43]
## Versions

**shapiq version**:
**Python version**:
**Operating system**:

## Steps/code to reproduce

```python
# Sample code to reproduce the problem
# Please do your best to provide a Minimal, Reproducible Example: https://stackoverflow.com/help/minimal-reproducible-example
```

**Comment by mmschlk** [comment]
![Untitled](https://github.com/mmschlk/shapiq/assets/45100845/893ee66d-526e-42f2-82c6-97e5edbc964f)
