### ISSUE TITLE
Add Test to TabularExplainer comparing against SHAP implementation

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#62]
We should have a test comparing the output of the TabularExplainer against the output of the KernelSHAP implementation of the well known shap package. 

This test does not need to be a perfect result in terms of the exact same values. This of course will only work for first order interactions (SVs).

**Comment by mmschlk** [comment]
A way of doing this is to run shap on a fixed model locally on your machine and copy the results from SHAP into the test case. I would like to omit having shap as a dependency in our test environment because it is too unreliable.

I did this similarly in the treeshap-iq comparison: https://github.com/mmschlk/shapiq/blob/d4f0d45eca24d95a174e74779ae87134ed107523/tests/tests_explainer/tests_tree_explainer/test_tree_treeshapiq.py#L84

**Comment by hbaniecki** [comment]
this will work for `max_order=1`, which currently throws `ValueError: The maximum order must be at least 2.`

**Comment by mmschlk** [comment]
SHAP is a bit unstable and benchmark and exact computer is the better comparison/check.
