### ISSUE TITLE
Add Stratified Sampling SV Approx

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#72]
Add the stratified sampling SV approximator.

# Tasks
- [ ] Add the approximator
- [ ] Add tests
- [ ] Add the documentation and the correct citation to the estimator

**Comment by kolpaczki** [comment]
The algorithm as stated in the paper (Maleki et al., 2013) uses a specific distribution of sampled marginal contributions over the sizes 0 to n-1 which performs very poorly empirically. I will implement a uniform distribution such that for each player marginal contributions to coalitions of different size are sampled with equal frequency.

**Comment by kolpaczki** [comment]
The paper (Maleki et al., 2013) does not specify how to approximate the Shapley values of all players. It only proposes an algorithm to approximate the Shapley value of a single fixed player. I will divide the available samples equally among all players.
