### ISSUE TITLE
Implement the `shapiq.Explainer(model, data)` class 

### ISSUE THREAD

**Issue by hbaniecki** [mmschlk/shapiq#87]
It could work like in `dalex`/`shap`, i.e. `shapiq.Explainer` finds the predict function and chooses tree / tabular explainer etc.

```python
import shapiq
explainer = shapiq.Explainer(model, X)
shapiq_values = explainer.explain(X)
```
see https://github.com/shap/shap?tab=readme-ov-file#tree-ensemble-example-xgboostlightgbmcatboostscikit-learnpyspark-models

**Comment by mmschlk** [comment]
Ah that is sexy, yes then users do not have to provide a model function but can also provide a model. In the future when there are other explainers it's also nice to extend. Like it very much. This could give the Explainer class more to do aswell.
